sms/sms/urls.py
from django.contrib import admin
from django.urls import path
from manageApp.views import depart, user, pretty, admin, account, order

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_del),
    path('depart/edit/<int:id>/', depart.depart_edit),

    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/edit/<int:nid>/', user.user_edit),
    path('user/delete/<int:nid>', user.user_delete),

    path('number/list/', pretty.num_list),
    path('number/add/', pretty.num_add),
    path('number/edit/<int:nid>', pretty.num_edit),
    path('number/delete/<int:nid>', pretty.num_delete),
    path('search/reset/', pretty.search_reset),

    path('admin/list/', admin.admin_list),
    path('public/add/', admin.admin_add),
    path('admin/edit/<int:nid>/', admin.admin_edit),
    path('admin/delete/<int:nid>', admin.admin_delete),
    path('admin/reset/<int:nid>', admin.admin_reset),
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/details/', order.order_details),
    path('order/edit/', order.order_edit),

]

sms/manageApp/models.py
from django.db import models


# Create your models here.
class Admin(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=128)
    password = models.CharField(verbose_name='密码', max_length=64)
    # signup_time = models.DateTimeField(verbose_name='注册时间', null=True, auto_now_add=True)
    signup_time = models.DateTimeField(verbose_name='注册时间', null=True, auto_now_add=True)
    update_time = models.DateTimeField(verbose_name='最后修改时间', null=True, auto_now=True)


class Department(models.Model):
    title = models.CharField(verbose_name='部门名称', max_length=32)

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    depart = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', on_delete=models.CASCADE)
    entry_time = models.DateTimeField(verbose_name='入职时间')

    gender_choice = (
        (1, '男'),
        (2, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choice)


class PrettyNum(models.Model):
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.FloatField(verbose_name='价格', default=0.0)
    level_choice = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级")
    )
    level = models.SmallIntegerField(verbose_name='级别', choices=level_choice, default=1)

    status_choice = (
        (1, '已占用'),
        (2, '未占用')
    )

    status = models.SmallIntegerField(verbose_name='状态', choices=status_choice, default=2)

class Order(models.Model):
    oid = models.CharField(verbose_name="订单号", max_length=64)
    title = models.CharField(verbose_name="名称", max_length=32)
    price = models.IntegerField(verbose_name="价格")

    status_choices = (
        (1, "待支付"),
        (2, "已支付"),
    )

    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name="管理员", to=Admin, on_delete=models.CASCADE)

sms/manageApp/views/account.py
from django.shortcuts import render, HttpResponse, redirect
from io import BytesIO
from manageApp.model_card import *
from manageApp.utils import generate_code


def login(request):
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        system_code = request.session.get("image_code", "")
        user_code = form.cleaned_data.pop("user_code")
        if system_code.upper() != user_code.upper():
            form.add_error("user_code", '验证码错误')
            return render(request, 'login.html', {'form': form})
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})
        request.session['info'] = {'id': admin_object.id, 'name': admin_object.username}
        return redirect('/admin/list/')
    return render(request, 'login.html', {'form': form})


def logout(request):
    """ 注销 """

    request.session.clear()

    return redirect('/login/')


def image_code(request):
    """ 生成图片验证码 """

    # 调用pillow函数，生成图片
    img, code_string = generate_code.check_code()
    print(code_string)

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给Session设置60s超时
    request.session.set_expiry(60 * 60 * 24)

    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())

sms/manageApp/views/admin.py
from django.shortcuts import render, redirect
from manageApp.model_card import *
from manageApp.utils.pagination import Pagination
from manageApp.model_card import AdminModel


def admin_list(request):
    q_value = request.GET.get('q', '')
    search_condition = dict()
    if q_value:
        search_condition["username__contains"] = q_value

        query = models.Admin.objects.filter(**search_condition)
    else:
        query = models.Admin.objects.all()
    pagination_object = Pagination(
        request=request,
        query=query
    )
    finall_query, page_list_show, page, page_total_size = pagination_object.pagination()
    return render(request, 'admin_list.html', {'query': finall_query,
                                               'search_data': q_value,
                                               'page_list_show': page_list_show,
                                               'current_page': page,
                                               'page_total_size': page_total_size})


def admin_add(request):
    if request.method == 'GET':
        form = AdminModel()
        return render(request, 'admin_add.html', {'form': form, 'entity': '添加管理员'})

    form = AdminModel(data=request.POST)
    # form.signup_time = timezone.datetime.now()
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'admin_add.html', {'form': form, 'entity': '添加管理员', 'time_type': 'signup_time'})


def admin_edit(request, nid):
    raw = models.Admin.objects.filter(id=nid).first()
    if not raw:
        return render(request, 'admin_update_error.html', {'msg': '数据不存在！'})
    if request.method == 'GET':
        form = AdminEditModelForm(instance=raw)
        return render(request, 'admin_add.html', {'form': form, 'entity': '修改管理员信息'})
    form = AdminEditModelForm(data=request.POST, instance=raw)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'admin_add.html', {'form': form, 'entity': '修改管理员信息'})


def admin_reset(request, nid):
    """ 重置密码 """
    # 对象 / None
    row_object = models.Admin.objects.filter(id=nid).first()
    if not row_object:
        return redirect('/admin/list/')

    entity = "正在重置用户`{}`的密码".format(row_object.username)

    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request, 'admin_add.html', {"form": form, "entity": entity})
    # instance=obj让当前对象显示默认值
    form = AdminResetModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'admin_add.html', {"form": form, "entity": entity})


def admin_delete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')

sms/manageApp/views/depart.py
from django.shortcuts import render, redirect
from manageApp.model_card import *

def depart_list(request):
    query_set = models.Department.objects.all()

    return render(request, 'depart_list.html', {'query_set': query_set})


def depart_add(request):
    if request.method == 'GET':
        return render(request, 'depart_add.html')

    title = request.POST.get("title")
    models.Department.objects.create(title=title)
    return redirect("/depart/list/")


def depart_del(request):
    nid = request.GET.get("nid")
    models.Department.objects.filter(id=nid).delete()

    return redirect('/depart/list/')


def depart_edit(request, id):
    if request.method == 'GET':
        depart_obj = models.Department.objects.filter(id=id).first()
        return render(request, 'depart_edit.html', {'depart_obj': depart_obj})
    title = request.POST.get('title')
    models.Department.objects.filter(id=id).update(title=title)
    return redirect('/depart/list/')

sms/manageApp/views/order.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from manageApp.model_card import *
from manageApp.utils.pagination import Pagination
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime
import random
import json


def order_list(request):
    query = models.Order.objects.all().order_by('-id')
    pagination_object = Pagination(
        request=request,
        query=query
    )
    form = OrderModelForm()
    final_query, page_list_show, page, page_total_size = pagination_object.pagination()
    return render(request, 'order_list.html', {
        'form': form,
        'query': final_query,
        'page_list_show': page_list_show,
        'current_page': page,
        'page_total_size': page_total_size})


@csrf_exempt
def order_add(request):
    form = OrderModelForm(data=request.POST)
    if form.is_valid():
        admin_id = request.session['info']['id']
        form.instance.oid = datetime.now().strftime("%Y%m%d%H%M%S") + str(admin_id) + chr(random.randint(65, 90))
        form.instance.admin_id = admin_id
        form.save()
        return HttpResponse(json.dumps({"status": True}))
    return HttpResponse(json.dumps({"status": False, "error": form.errors}))


def order_delete(request):
    uid = request.GET.get('uid')
    if models.Order.objects.filter(id=uid).exists():
        models.Order.objects.filter(id=uid).delete()
        return HttpResponse(json.dumps({
            'status': True
        }))
    return HttpResponse(json.dumps(
        {
            'status': False,
            'error': '删除失败，数据不存在！'
        }
    ))


def order_details(request):
    uid = request.GET.get('uid')
    request_query = models.Order.objects.filter(id=uid).values("title", 'price', 'status').first()
    if not request_query:
        return JsonResponse({'status': False, 'error': '数据不存在！'})
    request_query = {
        'status': True,
        'data': request_query
    }
    return JsonResponse(request_query)


@csrf_exempt
def order_edit(request):
    uid = request.GET.get('uid')
    row_object = models.Order.objects.filter(id=uid).first()
    if not row_object:
        return JsonResponse({'status': False, 'unexist_error': '数据不存在，请刷新重试'})
    form = OrderModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    else:
        return JsonResponse({'status': False, 'error': form.errors})

sms/manageApp/views/pretty.py
from django.shortcuts import render, redirect
from manageApp.model_card import *
from manageApp.utils.pagination import Pagination


def num_list(request):
    # import random
    # for j in range(300):
    #     models.PrettyNum.objects.create(mobile=str(18812345678+j), price=100, level=random.randint(1, 10), status=random.randint(1, 2))
    q_value = request.GET.get('q', '')
    search_condition = dict()
    if q_value:
        search_condition["mobile__contains"] = q_value

    query = models.PrettyNum.objects.filter(**search_condition).order_by('id')
    pagination_object = Pagination(
        request=request,
        query=query
    )
    finall_query, page_list_show, page, page_total_size = pagination_object.pagination()
    return render(request, 'number_list.html', {'query': finall_query,
                                                'search_data': q_value,
                                                'page_list_show': page_list_show,
                                                'current_page': page,
                                                'page_total_size': page_total_size})


def search_reset(request):
    return redirect('/number/list/')


def num_add(request):
    if request.method == 'GET':
        form = PrettyModel()
        return render(request, 'number_add.html', {'form': form})
    form = PrettyModel(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/number/list/')
    return render(request, 'number_add.html', {'form': form})


def num_edit(request, nid):
    raw = models.PrettyNum.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = PrettyEditModel(instance=raw)
        return render(request, 'number_edit.html', {'form': form})
    form = PrettyEditModel(data=request.POST, instance=raw)
    if form.is_valid():
        form.save()
        return redirect('/number/list/')
    return render(request, 'user_edit.html', {'form': form})


def num_delete(request, nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/number/list/')

sms/manageApp/views/user.py
from django.shortcuts import render, redirect
from manageApp.model_card import *


def user_list(request):
    query = models.UserInfo.objects.all()
    return render(request, 'user_list.html', {'query': query})


def user_add(request):
    if request.method == 'GET':
        form = UserModel()
        return render(request, 'user_add.html', {'form': form})

    form = UserModel(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')

    return render(request, 'user_add.html', {'form': form})


def user_edit(request, nid):
    raw = models.UserInfo.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = UserModel(instance=raw)
        return render(request, 'user_edit.html', {'form': form})
    form = UserModel(data=request.POST, instance=raw)
    if form.is_valid():
        form.save()
        return redirect('/user/list/')
    return render(request, 'user_edit.html', {'form': form})


def user_delete(request, nid):
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list/')

sms/manageApp/templates/admin_update_error.html
{% extends 'layout.html' %}

{% block content %}
    <div>
        <h3 style="margin-left: 20px">{{ msg }}</h3>
    </div>
{% endblock %}

sms/manageApp/templates/number_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">

        <div style="margin-bottom: 10px">
            <a href="/number/add/" class="btn btn-success">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建号码
            </a>
            <div class="col-lg-6" style="float: right;width: 350px">
                <form method="get">
                    <cdiv class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="请输入搜索条件..."
                               value={{ search_data }}>
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit" style="width: 60px">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                            <a class="btn btn-default" href="/search/reset/">重置</a>
                        </span>
                    </cdiv><!-- /input-group -->
                </form>
            </div><!-- /.col-lg-6 -->
            <div style="clear: both"></div>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true" style="margin-right: 3px"></span>账号列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>价格</th>
                    <th>级别</th>
                    <th>状态</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in query %}
                    <tr>
                        <td>{{ obj.id }}</td>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>

                            <a href="/number/edit/{{ obj.id }}" class="btn btn-primary btn-xs">编辑</a>
                            <a href="/number/delete/{{ obj.id }}" class="btn btn-danger btn-xs">删除</a>

                        </td>

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <nav aria-label="...">
            <ul class="pagination">
                {#                <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>#}
                {#                <li><a href="#">1</a></li>#}
                {#                <li><a href="#">2</a></li>#}
                {#                <li><a href="#">3</a></li>#}
                {#                <li><a href="#">4</a></li>#}
                {#                <li><a href="#">5</a></li>#}
                {{ page_list_show }}

                {#                <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>#}
                <li>
                    <form style="float: left" method="get">
                        <input type="text" class="form-control" name="page"
                               style="float: left;border-radius: 0;width: 55px;display: inline-block" placeholder="页码">
                        <span style="margin-left: 0;float: left">
                            <button class="btn btn-default" style="border-radius: 0;" type="submit">跳转</button>
                        </span>
                        <span style="margin-left: 6px; margin-top: 16px; float: left">
                            &lt 第{{ current_page }}页/共{{ page_total_size }}页 &gt
                        </span>
                    </form>
                </li>

            </ul>
        </nav>
    </div>
{% endblock %}

sms/manageApp/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    <style>
        .btn-container {
            display: flex;
            justify-content: flex-end;
        }

    </style>
    <div class="container">
        <div>
            <!--input type="button" value="新建订单" class="btn btn-primary" data-toggle="modal" data-target="#myModal"-->
            <input type="button" id="btnAdd" value="新建订单" class="btn btn-success" style="margin-bottom: 10px">
        </div>
        <!--order_list-->
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>订单号</th>
                    <th>名称</th>
                    <th>价格</th>
                    <th>状态</th>
                    <th>管理员</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in query %}
                    <tr uid="{{ obj.id }}">
                        <th>{{ obj.id }}</th>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.admin.username }}</td>
                        <td>
                            <input uid="{{ obj.id }}" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">
                            <input uid="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete" type="button" value="删除">
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <nav aria-label="...">
            <ul class="pagination">
                {#                <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>#}
                {#                <li><a href="#">1</a></li>#}
                {#                <li><a href="#">2</a></li>#}
                {#                <li><a href="#">3</a></li>#}
                {#                <li><a href="#">4</a></li>#}
                {#                <li><a href="#">5</a></li>#}
                {{ page_list_show }}

                {#                <li><a href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>#}
                <li>
                    <form style="float: left" method="get">
                        <input type="text" class="form-control" name="page"
                               style="float: left;border-radius: 0;width: 55px;display: inline-block" placeholder="页码">
                        <span style="margin-left: 0;float: left">
                            <button class="btn btn-default" style="border-radius: 0;" type="submit">跳转</button>
                        </span>
                        <span style="margin-left: 6px; margin-top: 16px; float: left">
                            &lt 第{{ current_page }}页/共{{ page_total_size }}页 &gt
                        </span>
                    </form>
                </li>

            </ul>
        </nav>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">
                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error-msg" style="color: #ff0000;position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">

            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4>确定删除？</h4>
                <p style="margin-bottom: 10px">删除后，其关联数据会被同时删除，操作不可恢复，请谨慎操作！</p>
                <p class="btn-container">
                    <button type="button" class="btn btn-default cancel" style="margin-right: 10px">
                        不用了，谢谢
                    </button>
                    <button id="btn-confirm-delete" type="button" class="btn btn-danger">仍要删除</button>
                </p>
            </div>

        </div>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bingBtnCancelDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $('#btnAdd').click(function () {
                    $('#formAdd')[0].reset();
                    $('#myModalLabel').text('新建商品信息')
                    $('#myModal').modal('show');
                }
            );
        }

        function bindBtnSaveEvent() {
            $('#btnSave').click(function () {
                    $(".error-msg").empty();
                    if (EDIT_ID) {
                        editSave();
                        EDIT_ID = undefined;
                    } else {
                        eventAdd();
                    }
                }
            );
        }

        function bindBtnDeleteEvent() {
            $('.btn-delete').click(function () {
                $('#deleteModal').modal('show');
                DELETE_ID = $(this).attr('uid');

            });
        }

        function bindBtnConfirmDeleteEvent() {
            $('#btn-confirm-delete').click(
                function () {
                    $.ajax(
                        {
                            url: '/order/delete/',
                            type: 'get',
                            data: {
                                uid: DELETE_ID
                            },
                            dataType: 'JSON',
                            success: function (res) {
                                if (res.status) {
                                    {#$('#deleteModal').modal('hide');#}
                                    location.reload();
                                } else {
                                    alert(res.error);
                                }

                            }
                        }
                    );
                }
            )

        }

        function bingBtnCancelDeleteEvent() {
            $('.close, .cancel').on('click', function () {
                $('#deleteModal').modal('hide');
                DELETE_ID = 0;
                location.reload();

            });

        }

        function bindBtnEditEvent() {
            $('.btn-edit').click(function () {
                var uid = $(this).attr("uid");
                EDIT_ID = uid;
                $('#myModalLabel').text('编辑商品信息')
                $.ajax(
                    {
                        url: '/order/details/',
                        type: 'get',
                        data: {
                            uid: uid,
                        },
                        dataType: 'JSON',
                        success: function (res) {
                            if (res.status) {
                                $.each(res.data, function (name, value) {
                                    $('#id_' + name).val(value)
                                })
                                $('#myModal').modal('show');
                            } else {
                                alert(res.error)
                            }
                        }
                    }
                )
            })
        }

        function eventAdd() {
            $.ajax(
                {
                    url: '/order/add/',
                    type: 'post',
                    data: $('#formAdd').serialize(),
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            $('#formAdd')[0].reset();
                            $('#myModal').modal('hide');
                            location.reload();
                        } else {
                            console.log(res.error)
                            $.each(res.error, function (name, errorlist) {
                                $('#id_' + name).next().text(errorlist[0])
                            })
                        }
                    }

                }
            )
        }

        function editSave() {
            var uid;
            uid = EDIT_ID;
            $.ajax(
                {
                    url: '/order/edit/' + '?uid=' + EDIT_ID,
                    type: 'post',
                    data: $('#formAdd').serialize(),
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            $('#formAdd')[0].reset();
                            $('#myModal').modal('hide');
                            location.reload();
                        } else {
                            if (res.unexist_error) {
                                alert(res.unexist_error)
                            } else {
                                console.log(res.error)
                                $.each(res.error, function (name, errorlist) {
                                    $('#id_' + name).next().text(errorlist[0])
                                })
                            }
                        }
                    }
                }
            )
        }
    </script>
{% endblock %}

sms/manageApp/templates/user_edit.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">编辑用户</h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}: {{ field }}</label>
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_entry_time').datepicker(
                {
                    format: 'yyyy-mm-dd',
                    startData: '0',
                    language: 'zh-CN',
                    autoclose: true
                }
            );
        })
    </script>
{% endblock %}